version: 2
updates:
  - package-ecosystem: docker
    directory: /blockchain-explorer
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /ton-compile-source
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /ton-full-node
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /ton-full-node/scripts
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /ton-http-config
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /ton-toncenter
    schedule:
      interval: weekly
